replicaCount: 1

image:
  tag: "master"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: api.ip.mirix.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api.ip.mirix.io
      hosts:
        - api.ip.mirix.io

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi