replicaCount: 1

image:
  repository: ghcr.io/stiviik/th-ro-ip-2021/frontend
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: "regcred"
nameOverride: "throip-frontend"
fullnameOverride: "throip-frontend"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
#  capabilities:
#    drop:
#      - ALL
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 65532

service:
  type: ClusterIP
  port: 8080

nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64

tolerations: []

affinity: {}