replicaCount: 1

image:
  repository: acr0dev0throip20210de.azurecr.io/frontend
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "throip-frontend"
fullnameOverride: "throip-frontend"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
#  capabilities:
#    drop:
#      - ALL
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 65532

service:
  type: ClusterIP
  port: 8080

nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64

tolerations: []

affinity: {}