name: Frontend

on:
  schedule:
    - cron:  '0 5 * * 0'
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - '.github/workflows/frontend.yaml'
      - 'src/frontend/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/metadata-action@v3
        id: meta
        name: Docker meta
        with:
          images: ghcr.io/StiviiK/th-ro-ip-2021/frontend
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - uses: docker/setup-qemu-action@v1
        name: Set up QEMU
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
      - uses: docker/login-action@v1 
        name: Login to ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2.6.1
        with:
          context: './src/frontend'
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --namespace default --install -f src/frontend/Helm/values.yaml -f src/frontend/Helm/dev.values.yaml --set "image.tag=sha-${GITHUB_SHA::7}" throip-frontend src/frontend/Helm
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'